### ISSUE TITLE
No "New launch Target" for Eclipse 2022-09 (IEP-863)

### ISSUE THREAD

**Issue by Samuel-Zhang-Rheem** [espressif/idf-eclipse-plugin#684] opened 2023-01-29 09:05 UTC
**Describe the bug**
Eclipse 2022-09  without configuration bar.
After generating a new ESP project, no "sdkconfig" file, no "configuration"bar, I can't setup the target type.

**To Reproduce**

**Expected behavior**

**Screenshots**

![No Configuration Bar](https://user-images.githubusercontent.com/23248423/215316156-fb6dd198-067a-4b31-8da2-305886c9bd2b.png)

**Espressif-IDE Product Information:**
[Espressif Product Information.txt](https://github.com/espressif/idf-eclipse-plugin/files/10529412/Espressif.Product.Information.txt)

**Eclipse Error log:** 
Window > Show View > Other > Search for "Error Log" (Attach as a file)
[.log](https://github.com/espressif/idf-eclipse-plugin/files/10529414/default.log)

**Comment by sigmaaa** [comment] 2023-01-29 11:17
Hi @Samuel-Zhang-Rheem, 
Thank you for reporting this. sdkconfig file will be generated after the build. 
Can you check, please, if there is an option in the eclipse preference to enable the launch bar: 
<img width="838" alt="Screenshot 2023-01-29 at 13 03 49" src="https://user-images.githubusercontent.com/24419842/215322385-6cc01ab9-c6bc-4337-b9fe-a6bb37c44898.png">

**Comment by Samuel-Zhang-Rheem** [comment] 2023-01-29 13:15
Hello,

The PC with Eclipse 2022 has this problem.
After tick "Enable the launch Bar", I can view the configuration, problem fixed.

Another PC with Eclipse 2021 without this issue.

Is it causing by Eclipse version 2022 or something wrong with my installation?

Regards
Sam

**Comment by sigmaaa** [comment] 2023-01-29 15:34
Hi @Samuel-Zhang-Rheem, 
Eclipse 2022 is not a problem. I have seen similar issues reported on Eclipse 2020 and 2021. Looks like there is a case when the launch bar is disabled by default after installation. It should normally be enabled by default after installation. I was never able to reproduce it, so it's hard to tell what is going wrong. Is it freshly installed Eclipse 2022 or it had some plugins installed?

**Comment by Samuel-Zhang-Rheem** [comment] 2023-02-02 06:58
There is a project, I can build it successfully in windows CMD line.
But in Eclipse, Terminal, run command line; when I go into " user\esp\esp-idf" directory, run "export.sh", it prompt "How do you to open this file",
something wrong with "Eclipse settings"?

**Comment by kolipakakondal** [comment] 2023-02-02 07:53
> export.sh

Use export.bat as mentioned here https://docs.espressif.com/projects/esp-idf/en/release-v4.2/esp32/get-started/windows-setup-update.html#add-esp-idf-tools-to-path-using-an-export-script

However, when you're working in Eclipse environment, always run "Espressif > ESP-IDF Install Tools > Install Tools" this will install missing tools and run export command to configure the required paths in the CDT build environment

**Comment by Samuel-Zhang-Rheem** [comment] 2023-02-06 11:45
export.bat    works.
But there is another problem:
After I update a plugin for python editor, I can't build project which is was built successfully before.
The report error message:

_Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project 'station'.
'int com.espressif.idf.core.build.IDFBuildConfiguration.watchProcess(java.lang.Process, org.eclipse.cdt.core.resources.IConsole)'_

How to fix it?

**Comment by whoiswentz** [comment] 2023-02-12 01:31
> export.bat works. But there is another problem: After I update a plugin for python editor, I can't build project which is was built successfully before. The report error message:
> 
> _Errors occurred during the build. Errors running builder 'CDT Core Builder' on project 'station'. 'int com.espressif.idf.core.build.IDFBuildConfiguration.watchProcess(java.lang.Process, org.eclipse.cdt.core.resources.IConsole)'_
> 
> How to fix it?

I'm getting this error, someone knows how to fix? It's impossible to use this plugin due this error

**Comment by kolipakakondal** [comment] 2023-02-13 06:31
Hi @Samuel-Zhang-Rheem 

Could you our latest Espressif-IDE 2.8.1 Windows Installer and see if that helps?
https://github.com/espressif/idf-installer/releases/download/espressif-ide-2.8.1-esp-idf-5.0/espressif-ide-setup-2.8.1-with-esp-idf-5.0.exe

**Comment by kolipakakondal** [comment] 2023-04-13 04:05
>Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project 'station'.
'int com.espressif.idf.core.build.IDFBuildConfiguration.watchProcess(java.lang.Process, org.eclipse.cdt.core.resources.IConsole)'

This issue is fixed with IEP [v2.9.1](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.9.1) release, hence closing the issue.

**Closed** 2023-04-13 04:05 UTC
