### ISSUE TITLE
NullPointerException while building - macOS Catalina 10.15.3 (IEP-138)

### ISSUE THREAD

**Issue by eliaxyz** [espressif/idf-eclipse-plugin#56] opened 2020-02-23 12:48 UTC
After installing and starting with the example project "blink", everything works fine, but after closing eclipse and restarting, there occurs always an Java-Error:

```
Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project 'test3'.
java.lang.NullPointerException
```

Because of this error, build will not complete.
In the console is shown:

```
Building in: /Users/eli/esp/eclipse/test1/build
cmake --build . -- -v
[1/3] cd /Users/eli/esp/eclipse/test1/build/bootloader && /Users/eli/.espressif/tools/cmake/3.13.4/CMake.app/Contents/bin/cmake --build .
ninja: no work to do.
```

The Error-Log shows:

```
!SESSION 2020-02-23 16:21:48.793 -----------------------------------------------
eclipse.buildId=4.14.0.I20191210-0610
java.version=13.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.cpp.product -keyring /Users/eli/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.cpp.product -keyring /Users/eli/.eclipse_keyring

!ENTRY org.eclipse.core.net 1 0 2020-02-23 16:21:51.497
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY com.espressif.idf.core 1 0 2020-02-23 16:21:56.520
!MESSAGE idf_tools.py path: /Users/eli/esp/esp-idf/tools/idf_tools.py

!ENTRY com.espressif.idf.core 1 0 2020-02-23 16:21:56.701
!MESSAGE idf_tools.py export output: IDF_PYTHON_ENV_PATH=/Users/eli/.espressif/python_env/idf4.0_py2.7_env
OPENOCD_SCRIPTS=/Users/eli/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/share/openocd/scripts
PATH=/Users/eli/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:/Users/eli/.espressif/tools/esp32ulp-elf/2.28.51.20170517/esp32ulp-elf-binutils/bin:/Users/eli/.espressif/tools/cmake/3.13.4/CMake.app/Contents/bin:/Users/eli/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/bin:/Users/eli/.espressif/tools/ninja/1.9.0/:/Users/eli/.espressif/python_env/idf4.0_py2.7_env/bin:/Users/eli/esp/esp-idf/tools:$PATH

!ENTRY com.espressif.idf.core 1 0 2020-02-23 16:21:56.702
!MESSAGE PATH: /Users/eli/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:/Users/eli/.espressif/tools/esp32ulp-elf/2.28.51.20170517/esp32ulp-elf-binutils/bin:/Users/eli/.espressif/tools/cmake/3.13.4/CMake.app/Contents/bin:/Users/eli/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/bin:/Users/eli/.espressif/tools/ninja/1.9.0/:/Users/eli/.espressif/python_env/idf4.0_py2.7_env/bin:/Users/eli/esp/esp-idf/tools:$PATH

!ENTRY com.espressif.idf.core 1 0 2020-02-23 16:21:56.702
!MESSAGE [/Users/eli/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:/Users/eli/.espressif/tools/esp32ulp-elf/2.28.51.20170517/esp32ulp-elf-binutils/bin:/Users/eli/.espressif/tools/cmake/3.13.4/CMake.app/Contents/bin:/Users/eli/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/bin:/Users/eli/.espressif/tools/ninja/1.9.0/:/Users/eli/.espressif/python_env/idf4.0_py2.7_env/bin:/Users/eli/esp/esp-idf/tools:$PATH]

!ENTRY org.eclipse.core.resources 4 2 2020-02-23 16:22:07.635
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException
	at com.espressif.idf.core.build.IDFBuildConfiguration.processLine(IDFBuildConfiguration.java:421)
	at com.espressif.idf.core.build.IDFBuildConfiguration.processCompileCommandsFile(IDFBuildConfiguration.java:356)
	at com.espressif.idf.core.build.IDFBuildConfiguration.build(IDFBuildConfiguration.java:312)
	at org.eclipse.cdt.core.build.CBuilder.build(CBuilder.java:45)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:278)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:468)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:565)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:603)
	at org.eclipse.core.internal.resources.Project.build(Project.java:116)
	at org.eclipse.debug.core.model.LaunchConfigurationDelegate$1.run(LaunchConfigurationDelegate.java:412)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2312)
	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.buildProjects(LaunchConfigurationDelegate.java:419)
	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.buildForLaunch(LaunchConfigurationDelegate.java:123)
	at org.eclipse.launchbar.core.target.launch.LaunchConfigurationTargetedDelegate.superBuildForLaunch(LaunchConfigurationTargetedDelegate.java:61)
	at com.espressif.idf.launch.serial.internal.SerialFlashLaunchConfigDelegate.buildForLaunch(SerialFlashLaunchConfigDelegate.java:180)
	at org.eclipse.launchbar.ui.internal.commands.BuildActiveCommandHandler$1$1.run(BuildActiveCommandHandler.java:110)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Whenever I start a new project it works firstly... as long until I restart Eclipse.
But after restarting, there is no way to build the project again without aborting as described.

Also after restart, the code is shown as described in issue 43:
https://github.com/espressif/idf-eclipse-plugin/issues/43#issue-542925943

**Comment by kolipakakondal** [comment] 2020-02-24 06:56
Duplicate of https://github.com/espressif/idf-eclipse-plugin/issues/54 Hence closing it.

This issue has been fixed with the latest build, please get a new build https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.0.0-rc1

**Closed by kolipakakondal** 2020-02-24 06:56 UTC
Labels: duplicate
