### ISSUE TITLE
Eclipse 2020-09 unable to build with IDF-Eclipse Plugin (IEP-257)

### ISSUE THREAD

**Issue by martinloren** [espressif/idf-eclipse-plugin#141] opened 2020-10-07 10:13 UTC
**Describe the bug**
Eclipse IDF Plugin does not work with Eclipse 2020-09.

**To Reproduce**
1) Install latest Eclipse C+/C++ https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2020-09/R/eclipse-inst-jre-win64.exe
2) Install latest IDF Eclipse plugin installed
3) Eclipse unable to build new created projects

**Comment by kolipakakondal** [comment] 2020-10-07 10:50
Duplicate of https://github.com/espressif/idf-eclipse-plugin/issues/127

Hi @martinloren - Could you try this build and let us know how it goes https://github.com/espressif/idf-eclipse-plugin/issues/127#issuecomment-704122477

**Closed by kolipakakondal** 2020-10-07 10:50 UTC
