### ISSUE TITLE
[v.2.7.0] COM port locking after flashing  (IEP-814)

### ISSUE THREAD

**Issue by GTCLive** [espressif/idf-eclipse-plugin#638] opened 2022-12-02 18:57 UTC
**Describe the bug**
Hi, I'm using a ESP32-S3 and the JTAG port for both flashing and console monitoring. If I flash while the Terminal is connected it locks the port and the only way to unlock it is to close and restart Eclipse. This was not the case in v.2.6.0 where flashing while having Terminal connected at the same time worked quite well. Bug (nuisance) appeared after upgrading to v2.7.0. 

Workaround1: a) disconnect from Terminal b) flash c) reconnect to Terminal. 
Workaround2: Downgrade to v2.6.0 by Installing IDF Eclipse Plugin from Local Archive

**To Reproduce**
1. In Eclipse, connect to COM port via Terminal
2. Compile and flash to board
3. Go back to Terminal and you will see <Connecting...>

**Screenshots**
![espplugin1](https://user-images.githubusercontent.com/91785220/205365225-ef4d4206-a1ee-4cb1-b1df-50dfa645c726.jpg)

![espplugin2](https://user-images.githubusercontent.com/91785220/205365277-63567a9e-a4b5-4702-b614-44610d971a01.jpg)

**Comment by userbogd** [comment] 2022-12-10 10:55
I have the same issue after update plugin to version 2.7. Rollback to 2.6 fix this behaviour. As temporary solution i manually disconnect from terminal before flash the device, every time. If forget to do it, it will be neccessary kill python process of eclipse restart.

**Comment by kolipakakondal** [comment] 2022-12-12 08:45
Hello, Sorry for the trouble. Could you please help us to troubleshoot this issue by identifying which process is holding the COM port?

Follow the instructions from here https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000YGw9CAG&l=en-US

**Comment by userbogd** [comment] 2022-12-12 09:45
The instruction you given can't find the process which locked the serial port. But i can point the process, which i killing for unlock. Also i guess you'll be interested in command line, starts this process. `"C:\Users\bogd\AppData\Local\Programs\Python\Python310\python.exe" C:\Users\bogd\esp-idf-v4.4.3\tools\idf_monitor.py -p \\.\COM6 -b 115200 --ws ws://localhost:53635 C:/BOGD-PROJECTS/dispHUB75/build/dispHUB75.elf` 
![2022-12-12](https://user-images.githubusercontent.com/48602838/207013388-bb684f1c-5f28-4c79-bc46-1e4003499b93.png)

**Comment by kolipakakondal** [comment] 2022-12-13 06:40
Hi @userbogd Thanks for sharing that. Most likely this is due to the core dump debugging feature which we introduced in v2.7.0 where websocket process might be holding the port

Will investigate further on this @alirana01

**Comment by sigmaaa** [comment] 2022-12-26 12:51
Hi @userbogd, @troky, @GTCLive,

Looks like this issue is fixed in the PR, which is still in review, but you can try these changes if you want. Here is [update](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489501999). 

Or if you don't want to affect your current Eclipse, you can try these changes on Espressif IDE: 
[Espressif IDE for Windows](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502003)
[Espressif IDE for Linux](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502000)
[Espressif IDE for mac](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502002)
[Espressif IDE for mac Arch64](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502001)

After installing Espressif IDE, click on Install Tools first, so environment variables will be set. Thank you

**Comment by userbogd** [comment] 2022-12-26 13:21
for me this fix works fine! thank you so much!

**Comment by troky** [comment] 2022-12-26 16:51
I can confirm it works fine now! Thanks.

**Comment by GTCLive** [comment] 2022-12-27 14:30
@sigmaaa
Apologies for the delay in trying this out and responding (xmas busy). I can also confirm the update works perfectly fine.
Amazing work and support, thank you so much. 

Let me know if you need this case closed now, or if you prefer leaving it open a bit longer for awareness.

**Comment by sigmaaa** [comment] 2022-12-27 16:07
Hi @GTCLive,

thank you for your feedback. Let's keep it open until the next release when we will include these changes. Thank you

**Comment by ddomnik** [comment] 2023-01-02 13:25
> Hi @userbogd, @troky, @GTCLive,
> 
> Looks like this issue is fixed in the PR, which is still in review, but you can try these changes if you want. Here is [update](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489501999).
> 
> Or if you don't want to affect your current Eclipse, you can try these changes on Espressif IDE: [Espressif IDE for Windows](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502003) [Espressif IDE for Linux](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502000) [Espressif IDE for mac](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502002) [Espressif IDE for mac Arch64](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502001)
> 
> After installing Espressif IDE, click on Install Tools first, so environment variables will be set. Thank you

Thanks for providing a fix. Could you please explain how to use it? 
I am on Windows. I tried to install com.espressif.idf.update.zip via Help > Install new Software, but all configs and the "Espressif" tab went missing after a restart.
Also tried to copy and replace the contents of the espressif-ide-win32.zip.zip into the IDE installation folder. But get JRE/JDK not found when starting.

Thanks

**Comment by userbogd** [comment] 2023-01-03 08:23
> but all configs and the "Espressif" tab went missing after a restart.

If you question is still not resolved. As mentioned in message your quoted, zip archive must be install over previously installed plugin. So, firstly install last released  plugin as link, and after install this patch as zip archived plugin. For me this sequence on Windows works fine.

**Comment by troky** [comment] 2023-01-03 08:52
I am using Eclipse 2022-12 with IDF plugin 2.7.0 and like @userbogd just installed provided zip via Help->Install New Software and everything worked. On Windows.

**Comment by kolipakakondal** [comment] 2023-01-03 09:12
> Eclipse 2022-12 with ID

I would recommend not using Eclipse 2022-12 as this is not officially supported and it also requires Java 17. 

https://github.com/espressif/idf-eclipse-plugin/issues/654

**Comment by troky** [comment] 2023-01-03 10:59
> I would recommend not using Eclipse 2022-12 as this is not officially supported and it also requires Java 17. Instead prefer Espressif-IDE v2.7.0 or Eclipse CDT 2022-09 with IEP plugin update

Yeah, I installed it without knowing about incompatibility but it works fine for me... also installed all possible updates. I guess I just had luck :)

**Closed** 2023-01-05 13:35 UTC

**Comment by f-hoepfinger-hr-agrartechnik** [comment] 2023-02-08 16:32
> Hi @userbogd, @troky, @GTCLive,
> 
> Looks like this issue is fixed in the PR, which is still in review, but you can try these changes if you want. Here is [update](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489501999).
> 
> Or if you don't want to affect your current Eclipse, you can try these changes on Espressif IDE: [Espressif IDE for Windows](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502003) [Espressif IDE for Linux](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502000) [Espressif IDE for mac](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502002) [Espressif IDE for mac Arch64](https://github.com/espressif/idf-eclipse-plugin/suites/10056670355/artifacts/489502001)
> 
> After installing Espressif IDE, click on Install Tools first, so environment variables will be set. Thank you

cool to see a Espressif IDE upcoming for Linux. 

very cool !!!!

**Comment by f-hoepfinger-hr-agrartechnik** [comment] 2023-02-08 16:55
are there Permanent links to the Espressif IDE ?

**Comment by sigmaaa** [comment] 2023-02-09 08:15
> are there Permanent links to the Espressif IDE ?

Hi @f-hoepfinger-hr-agrartechnik 
Espessif IDE different versions are available here https://github.com/espressif/idf-eclipse-plugin/releases

**Comment by f-hoepfinger-hr-agrartechnik** [comment] 2023-02-11 16:42
found it, thanks https://github.com/espressif/idf-eclipse-plugin/blob/master/docs/Espressif-IDE.md#downloads
