### ISSUE TITLE
SDK config editor incorrectly handle given value for partition table offset, as HEX without 0x...  (IEP-1037)

### ISSUE THREAD

**Issue by Maksons** [espressif/idf-eclipse-plugin#831] opened 2023-10-04 08:16 UTC
**Describe the bug**
SDK config editor incorrectly handle given value for partition table offset, as HEX without 0x... 

**To Reproduce**
1) Open SDK Config of project
2) Go to partition table
3) "Offset of partition table" has some !! decimal value !!!
4) Set "Offset of partition table" to 10000 (any other decimal value have problem too)
5) Press save ( Ctrl-S )
6) See wrong value (65536) in the same field ..

![image](https://github.com/espressif/idf-eclipse-plugin/assets/60009218/f522f898-9172-4bfe-ae35-7524ad09ad03)

 Ctrl-S
 
![image](https://github.com/espressif/idf-eclipse-plugin/assets/60009218/13acd5f8-ae4b-4f0f-9c8c-d66aa1f1da8c)

Espressif-IDE V2.11.0 
Linux Mint

**Comment by igrr** [comment] 2023-10-04 08:40
Can confirm, just recently ran into this issue as well.

**Comment by alirana01** [comment] 2023-11-27 08:05
The issue is being worked on and will be fixed with the new release.
https://github.com/espressif/idf-eclipse-plugin/pull/859

**Comment by alirana01** [comment] 2023-12-14 08:13
This PR is merged and closed, the issue will be fixed with latest release I am closing it now. Feel free to open it if you run into this issue after the upcoming release

**Closed by alirana01** 2023-12-14 08:13 UTC
Labels: bug
