### ISSUE TITLE
Not able to build with "Building Active Configuration" encountering a problem (IEP-244)

### ISSUE THREAD

**Issue by EvanS124** [espressif/idf-eclipse-plugin#129] opened 2020-09-21 00:38 UTC
Currently, I am on the Compiling a Project step on https://github.com/espressif/idf-eclipse-plugin/blob/master/README.md.
Whenever I click on build, I receive a dialogue box that says:
"Building Active Configuration" has encountered a problem. 
Errors occurred during the build.

Then on details its says:
Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project 'test'.
org/eclipse/cdt/utils/Platform

![Help](https://user-images.githubusercontent.com/70828941/93725941-35c9ec00-fb81-11ea-984d-a0b0ff021801.PNG)

**Expected behavior**
I expect my project to build properly.

**Comment by bseishen** [comment] 2020-09-21 03:02
Banging my head against the wall on this one too. I think this is the same issue. https://github.com/espressif/idf-eclipse-plugin/issues/127

**Comment by kifantidis** [comment] 2020-09-21 06:20
Hello. Which eclipse version do you have ??

**Comment by kolipakakondal** [comment] 2020-09-21 08:09
Hi All, 

We will provide the fix for this soon to support the Eclispe 2020-09 version. Please continue to use Eclipse 2020-06 until then.

**Comment by kolipakakondal** [comment] 2020-09-21 08:10
Duplicate of #127

**Closed by kolipakakondal** 2020-09-21 08:10 UTC

**Comment by EvanS124** [comment] 2020-09-21 23:19
> Hi All,
> 
> We will provide the fix for this soon to support the Eclispe 2020-09 version. Please continue to use Eclipse 2020-06 until then.

Downloading the 2020-06 version solved this problem. Thanks
