### ISSUE TITLE
Paths for Eclipse on Ubuntu 20.4 (IEP-585)

### ISSUE THREAD

**Issue by rdkluijv** [espressif/idf-eclipse-plugin#412] opened 2021-12-01 11:07 UTC
A fresh minimal install of Ubuntu 20.4. Installed all the needed packages and downloaded the espressif software. Build the Hello World application, downloaded it and checked with the monitor. Downloaded the Eclipse installer and installed Eclipse.
Installed the plugin according to the manual. Did a manual install using the existing directory. Restarted the computer.
Tried to use Tools manager but that did not work. Even the Browse button did not respond. Started configuring the environment variables. Changed it to the "new" paths for the espressif software. (At the end I pasted a copy.) There is some trouble here because cmake is in a different location and there is no ninja. 
Created a new Espressif IDF project. No buttons Next and Back so I could not load a Template. (Changed the $HOME to /home/rdkluijv. That fixed this problem. It seems that $HOME and $PATH are not expanded.) Configured the project and hit the hammer. This resulted in: "Build not configured correctly". Could change that to: 
"Building in: /home/rdkluijv/eclipse-workspace/Test00/build
No toolchain file found"
After I had added Core Build Toolchains. With the next step "Configuring CMake Toolchain" and restarting Eclipse I get the first error message back. Now I created a new project. Building this new project resulted in this error:
"Building in: /home/rdkluijv/eclipse-workspace/Test01/build
Configuring in: /home/rdkluijv/eclipse-workspace/Test01/build
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=/home/rdkluijv/esp/esp-idf/tools/cmake/toolchain-esp32.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCCACHE_ENABLE=1 -DIDF_TARGET=esp32 /home/rdkluijv/eclipse-workspace/Test01
Failure running cmake: "

Got it working. $PATH does not get expanded so /usr/bin had to be added to the path.
Additional installs: cmake, ccache and ninja.

Issue can be closed.

**Comment by kolipakakondal** [comment] 2021-12-22 02:43
> Got it working. $PATH does not get expanded so /usr/bin had to be added to the path.

Sorry for replying late on this. Is that something you have added manually to the eclipse CDT build environment variables or you have used Tools manager to install the tools, even then $PATH is not expanded variable value?

**Comment by rdkluijv** [comment] 2021-12-30 10:59
Installing problem was caused by the new release (5). I configured the environmental variable manual.
When I saw $PATH in the PATH below at the end I assumed I also could use $HOME as well.
So:
IDF_PATH
/Users/user-name/esp/esp-idf
Became:
$HOME/esp/esp-idf
That did not work.
To get other components to work I had to install a lower release and that worked perfect.

PATH
/Users/user-name/.espressif/tools/xtensa-esp32-elf/esp32-2019r1-8.2.0/xtensa-esp32-elf/bin:/Users/user-name/.espressif/tools/esp32ulp-elf/2.28.51.20170517/esp32ulp-elf-binutils/bin:/Users/user-name/.espressif/tools/cmake/3.13.4/CMake.app/Contents/bin:/Users/user-name/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/bin:/Users/user-name/.espressif/tools/ninja/1.9.0/:/Users/user-name/.espressif/python_env/idf4.0_py3.7_env/bin:/Users/user-name/esp/esp-idf/tools:$PATH

**Comment by alirana01** [comment] 2022-05-05 09:45
Closing as unable to reproduce with latest release

**Closed by alirana01** 2022-05-05 09:45 UTC
Labels: Ubuntu, Installation
