### ISSUE TITLE
Need ESP32-S3 buildin Jtag debug support (IEP-556)

### ISSUE THREAD

**Issue by ShenRen** [espressif/idf-eclipse-plugin#390] opened 2021-10-28 07:51 UTC
Debugging with esp32-S3's built-in Jtag fails.

**Comment by sigmaaa** [comment] 2021-11-09 08:19
Hi @ShenRen, 
can you provide openocd log with the error, please?

**Comment by kolipakakondal** [comment] 2022-02-14 11:53
Closing the issue due to lack of details. For the last two releases v2.4.0/v2.4.1, we have made a couple of enhancements and fixes, please verify with the latest one and see that helps.

**Closed by kolipakakondal** 2022-02-14 11:53 UTC
Labels: Debugging, JTAG

**Comment by bobby-RAD** [comment] 2022-12-01 15:34
This may be the issue @ShenRen was having. 

Hardware: ESP32-S3-DevkitC-1 v1.0
Espressif plugin:  V2.7.0
Problem:  Launch configs do not support ESP32S3-WROOM

The issue is that creating debug launch configs do not provide the option to specify ESP32-S3-WROOM under Board which requires esp32s3-builtin.cfg.  

A secondary issue is that run configs for this module which specify  "Flash Over JTAG" hang even with this workarond

Workaround:  Under Config options:

**Comment by kolipakakondal** [comment] 2022-12-02 05:57
> 
Hi @bobby-RAD Looks like `ESP32-S3-WROOM` board is added with the latest openOCD version [v0.11.0-esp32-20221026](https://github.com/espressif/openocd-esp32/releases/tag/v0.11.0-esp32-20221026)

reference
https://github.com/espressif/openocd-esp32/commit/610883f6520edf1d67478342f29d75531d93372c

To reflect this in the IDE, please make sure you have the latest tools. You can run `Espressif > ESP-IDF Tools Manager > Install Tools` 

![image](https://user-images.githubusercontent.com/8463287/205225165-38ab55a9-f9db-4231-9608-79c32853c492.png)

**Comment by bobby-RAD** [comment] 2022-12-02 18:00
Thank you @kolipakakondal. We are using idk v4.4.3. The plugin installs the following tools:

xecuting /usr/bin/python3 /Users/Shared/git/esp-idf/esp-idf-v4.4.3/tools/idf_tools.py list
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2021r2-patch5-8.4.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2021r2-patch5-8.4.0 (recommended, installed)
* xtensa-esp32s3-elf: Toolchain for Xtensa (ESP32-S3) based on GCC
  - esp-2021r2-patch5-8.4.0 (recommended, installed)
* xtensa-clang: LLVM for Xtensa (ESP32, ESP32-S2) based on clang (optional)
  - 12.0.1-d9341b81fc (recommended, installed)
* riscv32-esp-elf: Toolchain for 32-bit RISC-V based on GCC
  - esp-2021r2-patch5-8.4.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.35_20220830 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.23.1 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.11.0-esp32-20220706 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.10.2 (recommended, installed)

Presumably there could be dependencies between the tools and the idk version.
