### ISSUE TITLE
A new IDF project could not be created with Java 11. (IEP-188)

### ISSUE THREAD

**Issue by Ymoris** [espressif/idf-eclipse-plugin#86] opened 2020-05-26 11:57 UTC
A new IDF project could not be created.

The Eclipse workspe is home/user/eclipse-workspace.

The Finish button is inactive.

Is it necessary to uninstall and re-install the Eclipse ESP-IDF package?

The installation has been successful.

This the console content:
Executing python /home/user/esp-idf-v4.0.1/tools/idf_tools.py install all
Installing tools: xtensa-esp32-elf, esp32ulp-elf, cmake, openocd-esp32, ninja
Skipping xtensa-esp32-elf@esp-2019r2-8.2.0 (already installed)
Skipping esp32ulp-elf@2.28.51.20170517 (already installed)
Skipping cmake@3.13.4 (already installed)
Skipping openocd-esp32@v0.10.0-esp32-20190313 (already installed)
Skipping ninja@1.9.0 (already installed)

Executing python /home/user/esp-idf-v4.0.1/tools/idf_tools.py install-python-env
Requirement already satisfied: setuptools in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from -r /home/user/esp-idf-v4.0.1/requirements.txt (line 4)) (46.4.0)
Requirement already satisfied: click>=5.0 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from -r /home/user/esp-idf-v4.0.1/requirements.txt (line 8)) (7.1.2)
Requirement already satisfied: pyserial>=3.0 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from -r /home/user/esp-idf-v4.0.1/requirements.txt (line 9)) (3.4)
Requirement already satisfied: future>=0.15.2 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from -r /home/user/esp-idf-v4.0.1/requirements.txt (line 10)) (0.18.2)
Requirement already satisfied: cryptography>=2.1.4 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from -r /home/user/esp-idf-v4.0.1/requirements.txt (line 11)) (2.9.2)
Requirement already satisfied: pyparsing<2.4.0,>=2.0.3 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from -r /home/user/esp-idf-v4.0.1/requirements.txt (line 12)) (2.3.1)
Requirement already satisfied: pyelftools>=0.22 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from -r /home/user/esp-idf-v4.0.1/requirements.txt (line 13)) (0.26)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from cryptography>=2.1.4->-r /home/user/esp-idf-v4.0.1/requirements.txt (line 11)) (1.14.0)
Requirement already satisfied: six>=1.4.1 in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from cryptography>=2.1.4->-r /home/user/esp-idf-v4.0.1/requirements.txt (line 11)) (1.15.0)
Requirement already satisfied: pycparser in /home/user/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4->-r /home/user/esp-idf-v4.0.1/requirements.txt (line 11)) (2.20)
Installing Python packages from /home/user/esp-idf-v4.0.1/requirements.txt

Executing python /home/user/esp-idf-v4.0.1/tools/idf_tools.py export --format=key-value
OPENOCD_SCRIPTS=/home/user/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/share/openocd/scripts
IDF_PYTHON_ENV_PATH=/home/user/.espressif/python_env/idf4.0_py3.8_env
PATH=/home/user/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin:/home/user/.espressif/tools/esp32ulp-elf/2.28.51.20170517/esp32ulp-elf-binutils/bin:/home/user/.espressif/tools/cmake/3.13.4/bin:/home/user/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/bin:/home/user/.espressif/tools/ninja/1.9.0/:/home/user/.espressif/python_env/idf4.0_py3.8_env/bin:/home/user/esp-idf-v4.0.1/tools:$PATH

**Comment by kolipakakondal** [comment] 2020-05-26 12:13
Hi @Ymoris 

Could you send us the error log? Please follow the instructions from here https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by Ymoris** [comment] 2020-05-26 13:03
[Untitled.log](https://github.com/espressif/idf-eclipse-plugin/files/4682346/Untitled.log)

**Comment by kolipakakondal** [comment] 2020-05-26 14:03
Hi @Ymoris, Could you help me to verify this fix with the below local build
[com.espressif.idf.update-v1.0.1-66-gcb584069.zip](https://github.com/espressif/idf-eclipse-plugin/files/4682717/com.espressif.idf.update-v1.0.1-66-gcb584069.zip)

Please follow these instructions https://github.com/espressif/idf-eclipse-plugin#installPluginsUsingLocalFile

**Comment by Ymoris** [comment] 2020-05-26 18:21
Creation of a new project is OK
testblink project has been created from the example blink.
Terminal could be selected /dev/ttyUSB1 and message from the connected ESP32 could be received.

But could not found any ESP target. 

Click on the third dropdown
Select New Launch Target
Select ESP Target

**Comment by kolipakakondal** [comment] 2020-05-27 05:48
Check if this helps https://medium.com/@kondal.kolipaka/not-found-your-serial-port-for-your-esp-wrover-kit-board-7b9696d123c1

**Comment by kolipakakondal** [comment] 2020-05-27 05:52
> Creation of a new project is OK

So you're able to create a new project using the local build which I've provided?

**Comment by Ymoris** [comment] 2020-05-27 10:50
Yes, I am able to create a new project using the local build. 

The serial port is also available /dev/ttyUSB1.
If a terminal is opened, then I could receive a message from a pre-loaded program.

But, 

Select New Launch Target
Select ESP Target

is not available.

**Comment by kolipakakondal** [comment] 2020-05-27 12:30
Hi @Ymoris, I'm sorry, the issue is not very clear for me. You meant to say serial port **/dev/ttyUSB1** is not available in the new ESP Target wizard, but the same serial port is available in the Serial Terminal window?

**Comment by Ymoris** [comment] 2020-05-27 16:50
Sorry too.

 In fact ESP target wizard is not installed or accessible.

Yes, the serial port is available in the Serial Terminal window. I can open the Terminal dialogue box and setup the serial port. The Terminal could receive text from the connected ESP32 at /dev/ttyUSB1.

I can not compile and download the project to the ESP32 target. No icon or dialogue box related to an ESP target Wizard.

**Comment by kolipakakondal** [comment] 2020-05-28 06:03
If I understand correctly, you're not able to see Launch Target drop-down itself? Maybe you can share a screenshot/short video about the problem?

You can try the following options in combination and see if it helps.

- Make sure you're in the **C/C++** perspective
- Reset perspective
- Try to create a new project and see if you're able to see three drop-downs on the toolbar
- Restart eclipse

**Comment by Ymoris** [comment] 2020-05-28 11:14
If I understand correctly, you're not able to see Launch Target drop-down itself? Yes

I proceed with the  options and I can not see the launch Target drop-down itself.

Note: I am a beginner with Eclipse.


![C++ perspective](https://user-images.githubusercontent.com/65115374/83134745-ca7c7b80-a0b2-11ea-887a-5dd5a74cc165.png)

**Comment by kolipakakondal** [comment] 2020-05-29 05:26
That's an interesting issue.

Can you make sure "**Enable the Launch Bar**" is checked in the preferences?
<img width="623" alt="Screenshot 2020-05-29 at 10 55 11 AM" src="https://user-images.githubusercontent.com/8463287/83224432-0723a200-a19b-11ea-9285-0b62feb6575c.png">

**Comment by Ymoris** [comment] 2020-05-29 11:09
This is the launch preferences:

![Launch preferences](https://user-images.githubusercontent.com/65115374/83253404-ec413580-a17a-11ea-9a85-d09c966fb214.png)

Perspective is C/C++.

**Comment by kolipakakondal** [comment] 2020-05-29 12:23
How did you install Eclipse CDT? Looks like you've not installed the Eclipse CDT package as a whole. Probably, you would have updated the CDT on top of the standard Eclipse and forgot to select the LaunchBar feature.

As we mentioned here https://github.com/espressif/idf-eclipse-plugin#installing-prerequisites
> Eclipse 2018-12 CDT and above : Download and install Eclipse CDT package from here

Could you install this one https://www.eclipse.org/downloads/packages/release/2020-03/r/eclipse-ide-cc-developers-includes-incubating-components

**Comment by kolipakakondal** [comment] 2020-05-29 12:28
I could see CDT LaunchBar plugins in the log which you've provided. The issue might be something else. 

Anyway, please install the Eclipse CDT which I provided above, and see if it helps.

**Comment by Ymoris** [comment] 2020-05-29 13:36
After installing Eclipse CDT. This the screen shot.

The Launch  bar is there, but no Launch Configurations available.

![Launch bar](https://user-images.githubusercontent.com/65115374/83265634-c2ded480-a18f-11ea-8f1b-c364af79541a.png)

**Comment by Ymoris** [comment] 2020-05-29 15:05
After installing ESP tool chain with the provided com.espressif.idf.update-v1.0.1-66-gcb584069.zip.

The configuration is available.

I can build, but can not Run.

It seems that the serial port creates a issue. 

Note; The connected ESP32 is running a Arduino sketch.

See screen capture.

![Run](https://user-images.githubusercontent.com/65115374/83274307-9e88f500-a19b-11ea-9064-88e6b84ccea5.png)

**Comment by Ymoris** [comment] 2020-05-29 15:59
Finally, I reset the port to USB0 and get it Run.

The minor problem: The port is not retained in the terminal dialog box. Need to be rewite before run.

Thanks for your support.

This is the screen shot:
![Run successfull](https://user-images.githubusercontent.com/65115374/83279679-756c6280-a1a3-11ea-931d-166092982c86.png)

**Comment by kolipakakondal** [comment] 2020-06-03 07:28
Fixed java 11 issue with v1.1.0 release. Please update to the latest.
https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.1.0

**Closed by kolipakakondal** 2020-06-03 07:28 UTC
Labels: bug
