### ISSUE TITLE
Building hello_world example fails in Eclipse CDT 2022-12 with IDF Plugin v2.7 (IEP-828)

### ISSUE THREAD

**Issue by JBHunterI** [espressif/idf-eclipse-plugin#660] opened 2022-12-12 21:18 UTC
**Describe the bug**
IDF Eclipse Plugin v2.7 in **Eclipse CDT 2022-12** fails to build hello_world example, with or without all available Eclipse updates installed. Running 'idy.py build' from the same hello_world folder builds it successfully. 

**To Reproduce**
1. Download from eclipse.org, install, & launch Eclipse IDE for C/C++ Developers 2022-12, creating a new workspace
2. Follow github.com/espressif/idf-eclipse-plugin/blob/master/README.md to install IDF Eclipse Plugin v2.7.0
3. Accept all default values except check "Use an existing ESP-IDF directory from file system", choosing your existing %IDF_PATH% as ESP-IDF directory, and specifying %IDF_GIT_DIR%\git.exe, and %IDF_PYTHON_DIR%\python.exe
4. Select the correct Launch Target in the Eclipse Launch Bar that matches your ESP32 hardware target
5. Eclipse main menu File -> New -> Espressif IDF Project -> example -> hello_world
6. Ensure 'hello_world' Launch Configuration is active (gear -> Main tab -> "Flash over JTAG", OpenOCD Setup = Board: "ESP32-C3 chip (via builtin USB-JTAG)" in my case)
7. Ensure the 'Run' mode is active in the Launch Bar, then click its 'Build' icon (hammer tool)
8. Notice the "CDT Build Console [hello_world]" tab displays the top 3 "Building in: ...", "Configuring in: ...", and  "cmake -G Ninja ..." blue lines, but does not display the 4th black line:
      "-- Found Git: C:/App/ESP/IDF/tools/idf-git/2.34.2/cmd/git.exe (found version "2.34.1.windows.1")"
    and all subsequent build lines after. Instead, an Eclipse error window pops up (see **Screenshots** section below).

**Expected behavior**
Building hello_world example **succeeds** in Eclipse CDT 2022-12 with IDF Plugin v2.7, **as it does in Eclipse CDT 2022-09**, as well as with **'idf.py build' in the ESP-IDF 5.0 CMD shell**.

**Screenshots**
This is the Eclipse error that pops up after the top 3 build lines are displayed in the "CDT Build Console [hello_world]" tab:
![image](https://user-images.githubusercontent.com/117237895/207130185-a34ff086-fe44-4dac-b280-636da98d8168.png)

**Espressif-IDE Product Information:**
CDT Build environment variables
PATH: C:\App\ESP\IDF\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin;C:\App\ESP\IDF\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin;C:\App\ESP\IDF\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin;C:\App\ESP\IDF\tools\xtensa-esp32s2-elf\esp-2022r1-11.2.0\xtensa-esp32s2-elf\bin;C:\App\ESP\IDF\tools\xtensa-esp32s3-elf\esp-2022r1-11.2.0\xtensa-esp32s3-elf\bin;C:\App\ESP\IDF\tools\xtensa-clang\14.0.0-38679f0333\xtensa-esp32-elf-clang\bin;C:\App\ESP\IDF\tools\riscv32-esp-elf\esp-2022r1-11.2.0\riscv32-esp-elf\bin;C:\App\ESP\IDF\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;C:\App\ESP\IDF\tools\cmake\3.24.0\bin;C:\App\ESP\IDF\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin;C:\App\ESP\IDF\tools\ninja\1.10.2\;C:\App\ESP\IDF\tools\idf-exe\1.0.3\;C:\App\ESP\IDF\tools\ccache\4.6.2\ccache-4.6.2-windows-x86_64;C:\App\ESP\IDF\tools\dfu-util\0.9\dfu-util-0.9-win64;C:\App\ESP\IDF\esp-idf-v5.0\tools;C:/App/eclipseESP-IDF//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.5.v20221102-0933/jre/bin/server;C:/App/eclipseESP-IDF//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.5.v20221102-0933/jre/bin;C:\App\ESP\IDF\python_env\idf5.0_py3.8_env\Scripts;C:\App\ESP\IDF\tools\idf-git\2.34.2\cmd;C:\Program Files\Common Files\Oracle\Java\javapath;...my existing PATH...;;C:\App\eclipseESP-IDF;
ESP_IDF_VERSION: 5.0
OPENOCD_SCRIPTS: C:\App\ESP\IDF\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\share\openocd\scripts
IDF_CCACHE_ENABLE: 1
IDF_COMPONENT_MANAGER: 1
PYTHON_EXE_PATH: C:\App\ESP\IDF\python_env\idf5.0_py3.8_env\Scripts\python.exe
GIT_PATH: C:\App\ESP\IDF\tools\idf-git\2.34.2\cmd\git.EXE
IDF_TOOLS_PATH: C:\App\ESP\IDF
IDF_PATH: C:\App\ESP\IDF\esp-idf-v5.0
IDF_MAINTAINER: 1
IDF_PYTHON_ENV_PATH: C:\App\ESP\IDF\python_env\idf5.0_py3.8_env

Operating System: windows 10
Java Runtime Version: 17.0.5+8
Eclipse Version: 4.26.0.v20221123-1800
Eclipse CDT Version: 11.0.0.202211062329
IDF Eclipse Plugin Version: 2.7.0.202211101524
ESP-IDF v5.0
Python set for IDF_PYTHON_ENV: Python 3.8.7

**Eclipse Local (CONNECTED) Console:** 
Microsoft Windows [Version 10.0.19045.2311]
(c) Microsoft Corporation. All rights reserved.

C:\App\eclipseESP-IDF> cd %IDF_TOOLS_PATH%\esp*

C:\App\ESP\IDF\esp-idf-v5.0> where python git     
C:\App\ESP\IDF\python_env\idf5.0_py3.8_env\Scripts\python.exe
C:\App\ESP\IDF\tools\idf-git\2.34.2\cmd\git.exe

C:\App\ESP\IDF\esp-idf-v5.0> git describe --tag
v5.0

C:\App\ESP\IDF\esp-idf-v5.0> python --version
Python 3.8.7

**Comment by kolipakakondal** [comment] 2022-12-13 05:44
Hi @JBHunterI Sorry for the trouble. The IDF Eclipse Plugin does not yet support Eclipse CDT 2022-12. Could you please use Eclipse 2022-09 and 06 version?

Thanks for reporting this issue. We will update you as soon as we have a fix.

Duplicate of https://github.com/espressif/idf-eclipse-plugin/issues/654 hence closing this issue.

**Closed by kolipakakondal** 2022-12-13 05:44 UTC
