### ISSUE TITLE
Build issue with eclipse 20-09 (IEP-246)

### ISSUE THREAD

**Issue by alkosa** [espressif/idf-eclipse-plugin#131] opened 2020-09-21 11:06 UTC
**Describe the bug**
Hi,
I have tired to build a hello world project with eclipse 20-09, but I have got a message:
```bash
Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project 'hello-world'.
org/eclipse/cdt/utils/Platform
```
I have switched back to eclipse 20-06. It is working perfectly.

I do not know what is the problem.

Thank you very much for your help.

**Comment by kolipakakondal** [comment] 2020-09-21 11:17
Duplicate of https://github.com/espressif/idf-eclipse-plugin/issues/127

**Comment by ylj135cool** [comment] 2020-09-25 06:26
Right clicked the project of your workspace,Selectd Properties->Builders,remove the selection for CDT Core Builder,and rebuild it

**Comment by bheestand** [comment] 2020-09-30 21:05
Having same issue

**Comment by kolipakakondal** [comment] 2020-10-09 15:41
Hi All,

ESP-IDF Eclipse Plugin 1.2.3 is released to support Eclipse 2020-09
https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.2.3

Please update to the latest

**Closed** 2020-10-09 15:42 UTC
