### ISSUE TITLE
Unresolved inclusion: #include "freertos/FreeRTOS.h" (IEP-119)

### ISSUE THREAD

**Issue by psommerfeld** [espressif/idf-eclipse-plugin#48] opened 2020-01-25 05:33 UTC
Re-installed eclipse, ESP-IDF & tools, twice to make sure I didn't miss a step.
Tried to build "hello_world"
Got unresolved inclusions on:
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_spi_flash.h"

Saw some potential solutions to include certain directories in Project>Properties>C/C++ General> Paths and Symbols, but this choice doesn't exist in my project.
Another potential solution was right-click project and go to Properties>C/C++ Build but that doesn't exist either.

Others have fixed this by adding:
${IDF_PATH}/components/esp32/include
${IDF_PATH}/components/newlib/include
${IDF_PATH}/components/freertos/include
${IDF_PATH}/components/nvs_flash/include
${IDF_PATH}/components/driver/include
${IDF_PATH}/components/log/include
But WHERE do I add this in my setup?

**Comment by dpmcgabriel** [comment] 2020-01-27 03:00
Same problem here

**Comment by kolipakakondal** [comment] 2020-01-28 05:10
Thanks for reporting. It seems this issue appears only on Windows OS.  On macOS and Ubuntu it's working. 

This is a duplicate of https://github.com/espressif/idf-eclipse-plugin/issues/43

We will update it soon.

**Comment by ludo-d** [comment] 2020-02-05 17:41
same issue here.
indeed using windows environment.
in Ubuntu it is ok.

**Comment by samnangor** [comment] 2020-02-06 04:05
Same problem in window 7
could not find environment in project properties; yet it does exist in Preferences.
Build and flash are working fine. Even though most include header files show Unresolved inclusion.

**Comment by JAICHANGPARK** [comment] 2020-02-10 01:25
Any Update??

**Comment by kolipakakondal** [comment] 2020-02-10 07:59
Could you guys check this build and provide the feedback. **### This build works only if your windows user name doesn't have space in it!!!** since that's where all the tools are getting installed.  CMake is generating short paths if the path has space in it and that's causing an issue in Eclipse CDT. Until we provide a fix for this, please check this build.

Here is the build zip file to download 
https://github.com/kolipakakondal/idf-eclipse-plugin-dev/blob/master/com.espressif.idf.update-1.0.0.202002100648.zip

Installation instructions:
https://github.com/espressif/idf-eclipse-plugin#installing-idf-plugins-from-local-archive

**Comment by axbusch** [comment] 2020-02-10 21:48
For me this seems to work. No more include warnings

but now this 

![grafik](https://user-images.githubusercontent.com/42036054/74192894-b5402600-4c56-11ea-9711-a3169fb5b1a6.png)

[Log](https://gist.github.com/axbusch/5e585dab9f8eb766ddd2181ad0497145)
-

**Comment by JAICHANGPARK** [comment] 2020-02-11 00:00
@kolipakakondal Thanks for guide 
But I had still problem about 'unresolved inclusion'

![image](https://user-images.githubusercontent.com/19484515/74201281-a6845e00-4cac-11ea-9188-683b7e546248.png)

![image](https://user-images.githubusercontent.com/19484515/74201298-af752f80-4cac-11ea-92a4-6264e1218462.png)

![image](https://user-images.githubusercontent.com/19484515/74201345-d3d10c00-4cac-11ea-90bd-652c5391d64d.png)

Do I need any more settings ?

**Comment by JAICHANGPARK** [comment] 2020-02-11 00:08
Solved .. 

![image](https://user-images.githubusercontent.com/19484515/74201777-fb74a400-4cad-11ea-851a-a070b13bbd80.png)

@kolipakakondal Thank you

**Comment by samnangor** [comment] 2020-02-11 00:26
It is working fine with my win 10 and hello_world.
I will have to try with my win 7 to see if it is ok.

**Comment by JAICHANGPARK** [comment] 2020-02-11 00:43
after restarted I had this error.  

![image](https://user-images.githubusercontent.com/19484515/74203353-a7b88980-4cb2-11ea-93e5-75b94e0baf4b.png)


> For me this seems to work. No more include warnings
> 
> but now this
> 
> ![grafik](https://user-images.githubusercontent.com/42036054/74192894-b5402600-4c56-11ea-9711-a3169fb5b1a6.png)
> 
> ## Here is a logfile
> [Log](https://gist.github.com/axbusch/5e585dab9f8eb766ddd2181ad0497145)

**Comment by kolipakakondal** [comment] 2020-02-11 02:43
> after restarted I had this error.
> 
Sure, I'll check that

**Comment by kolipakakondal** [comment] 2020-02-11 11:15
@JAICHANGPARK @axbusch NPE issue got fixed, could you please verify this build https://github.com/kolipakakondal/idf-eclipse-plugin-dev/blob/master/com.espressif.idf.update-1.0.0.202002111040.zip

**Comment by JAICHANGPARK** [comment] 2020-02-12 02:05
@kolipakakondal It's works fine! Awesome

**Comment by kolipakakondal** [comment] 2020-02-12 07:34
Hi All, IDF Eclipse Plugin v1.0.0-beta5 (Build: 1.0.0.202002120536) is published to the update site. Please get the latest https://dl.espressif.com/dl/idf-eclipse-plugin/updates/latest/

**Closed** 2020-02-12 07:37 UTC
Labels: Windows, duplicate

**Comment by BorisDess** [comment] 2020-07-06 14:22
Installed eclipse today on a laptop, fresh install of everything.
Encountered the same problem.
Meh.
Tried VS ; worked.

**Comment by atom327i** [comment] 2020-10-05 21:04
Hello Guys!
I am trying to resolve the similar issue.
I have installed the Eclipse 2020.06CDT version with latest ESP-IDF. (from Friday)
As I create new ESP project based on any example, works fine.
But as I add any new component to be used, which obviously needs include files, includes will not be resolved. (I need to add the folders manually to Cmake.txt)
I copy the components to IDF Component folder

I have 20 years experience with SW engineeing, but I just starting with ESP32, so srry if I ask some trivial thing!
If somebody can have some hints i would appreciate it :)
Thanks!
